tests: Include common/include to fix tests
Now that cleanup.h depends on unique-name.h we must add
-Icommon/include in several tests.  Example error:

In file included from test-xz-curl.c:45:
../common/utils/cleanup.h:39:10: fatal error: unique-name.h: No such file or directory
   39 | #include "unique-name.h"
      |          ^~~~~~~~~~~~~~~