server/plugins.c: Simplify error handling of .block_size callback
In the case where an incorrect parameter was returned, the existing
code would emit several error messages, one for each problem, eg:

  error: plugin must set preferred block size to a power of 2
  error: plugin must set preferred block size between 512 and 32M

While technically correct, this worked unlike other error handling in
nbdkit.  In addition we could simplify the error handling flow.

Updates: commit 366c41f86f2846c742d0c42f110b70969fe3bf95