partition: Fix possible overflow when calculating if GPT disk is too small.
Found by Coverity:

Error: OVERFLOW_BEFORE_WIDEN (CWE-190): [#def4]
nbdkit-1.7.10/filters/partition/partition.c:217: overflow_before_widen: Potentially overflowing expression "2U * header.nr_partitions * header.partition_entry_size" with type "unsigned int" (32 bits, unsigned) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type "int64_t" (64 bits, signed).
nbdkit-1.7.10/filters/partition/partition.c:217: remediation: To avoid overflow, cast either "2U * header.nr_partitions" or "header.partition_entry_size" to type "int64_t".
  215|      * that the GPT header is bogus.
  216|      */
  217|->   if (size < 3*512 + 2*header.nr_partitions*header.partition_entry_size) {
  218|       nbdkit_error ("GPT partition table is too large for this disk");
  219|       return -1;