mingw: Avoid broken gnutls/socket.h header
gnutls 3.7.7 ships with a <gnutls/socket.h> that fails to compile on
mingw: https://gitlab.com/gnutls/gnutls/-/issues/1382.  But it also
provides a stub function gnutls_transport_is_ktls_enabled that always
returns false (since ktls is a Linux-only thing for now).  As such, we
are hitting compilation errors such as:

In file included from ../../server/crypto.c:59:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/gnutls/socket.h:32:10: fatal error: sys/socket.h: No such file or directory
   32 | #include <sys/socket.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

unless we also probe for whether the header works.  Noticed ever since
commit c4bc6d07 moved to newer lcitool that upgraded our CI mingw
environments into using the newer broken version of gnutls.

(cherry picked from commit 9defb48b3dc885559905078359946e54b3b34312)