python: Print readable tracebacks
We used traceback.format_exception, returning traceback lines. Join the
lines to make the tracebacks more readable.

Here is an example traceback:

$ ./nbdkit -f -v python tests/python-exception.py
...
nbdkit: debug: python: config_complete
nbdkit: error: tests/python-exception.py: config_complete: error: Traceback (most recent call last):
   File "tests/python-exception.py", line 51, in config_complete
    raise RuntimeError("this is the test string")
 RuntimeError: this is the test string

(cherry picked from commit a0606706041c21b8d9873b3b09c9cf549d307e1b)