gzip: Remove duplicate initialization of a field in the filter struct
Spotted by clang:

gzip.c:372:25: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
  .prepare            = gzip_prepare,
                        ^~~~~~~~~~~~
gzip.c:367:25: note: previous initialization is here
  .prepare            = gzip_prepare,
                        ^~~~~~~~~~~~
1 error generated.

(cherry picked from commit 1391449589c2b736c500042b8e05f18b1586b512)