Remove some C99-isms which break the build on RHEL 7
With gcc-4.8.5-44.el7.x86_64:

multi-conn.c: In function 'multi_conn_prepare':
multi-conn.c:209:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < groups.size; i++)
     ^
multi-conn.c:209:5: note: use option -std=c99 or -std=gnu99 to compile your code
multi-conn.c: In function 'multi_conn_finalize':
multi-conn.c:252:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < h->group->conns.size; i++) {
   ^
multi-conn.c:259:17: error: declaration of 'i' shadows a previous local [-Werror=shadow]
     for (size_t i = 0; i < groups.size; i++)
                 ^
multi-conn.c:252:15: error: shadowed declaration is here [-Werror=shadow]
   for (size_t i = 0; i < h->group->conns.size; i++) {
               ^
multi-conn.c:259:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < groups.size; i++)
     ^
cc1: all warnings being treated as errors

test-public.c: In function ‘test_nbdkit_parse_size’:
test-public.c:169:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < sizeof pairs / sizeof pairs[0]; i++) {
   ^
test-public.c:169:3: note: use option -std=c99 or -std=gnu99 to compile your code

(cherry picked from commit aacb5ecd7c062f4170c5dfdd3f44785e9891727a)