tests: ocaml: Rebuild test when OCaml library has changed.
Avoids this error:

Error: Files test_ocaml_plugin.cmx and ../plugins/ocaml/NBDKit.cmx
       make inconsistent assumptions over interface NBDKit
(cherry picked from commit b3a3a4a9bbfdc102d6a39e7a246b0f208933ecb5)