cache: Use correct type for reclaim_blk
We already prohibit images larger than 2^63, so there are not that
many blocks to worry about.  But using an unsigned type means our loop
is not quite right:

reclaim.c: In function ‘reclaim_lru’:
reclaim.c:162:24: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
  162 |   } while (reclaim_blk >= 0 && old_reclaim_blk != reclaim_blk);
      |                        ^~

Fixes: 602eb003
Signed-off-by: Eric Blake <eblake@redhat.com>
(cherry picked from commit c0d3f2c794f5e60df565321c070a3ae5cc1ea3b2)