rust: Use correct type of C char on ARM and RISC-V platforms
On ARM and RISC-V platforms, C char is unsigned (compared to signed on
other platforms).  This results in the error message attached when
compiling the rust plugin.  This problem has probably existed for a
long time, but I only tried to compile the bindings on riscv64 and
aarch64 today.

The fix is to use c_char instead of i8.  See:
https://stackoverflow.com/a/47684200

make: Entering directory '/home/rjones/d/nbdkit/plugins/rust'
cargo build --release
   Compiling nbdkit v0.2.0 (/home/rjones/d/nbdkit/plugins/rust)
error[E0308]: mismatched types
   --> src/lib.rs:985:19
    |
985 |             name: unsafe{ NAME.as_ptr() } as *const i8,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error[E0308]: mismatched types
   --> src/lib.rs:986:13
    |
986 |             longname,
    |             ^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error[E0308]: mismatched types
   --> src/lib.rs:987:13
    |
987 |             version,
    |             ^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error[E0308]: mismatched types
   --> src/lib.rs:988:13
    |
988 |             description,
    |             ^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error[E0308]: mismatched types
   --> src/lib.rs:993:13
    |
993 |             config_help,
    |             ^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error[E0308]: mismatched types
    --> src/lib.rs:1015:13
     |
1015 |             magic_config_key,
     |             ^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
     |
     = note: expected raw pointer `*const u8`
                found raw pointer `*const i8`

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `nbdkit`

To learn more, run the command again with --verbose.
make: *** [Makefile:1063: target/release/libnbdkit.rlib] Error 101
make: Leaving directory '/home/rjones/d/nbdkit/plugins/rust'