swab: Set err on unaligned client requests
Otherwise, nbdkit dies by assertion:
$ ./nbdkit --filter=swab pattern 128k -U - --run 'nbdsh -u $uri -c "h.pread(1,1)"'
nbdkit: pattern.0: error: swab: requests to this filter must be aligned
nbdkit: backend.c:485: backend_pread: Assertion `*err' failed.
Traceback (most recent call last):
...
nbd.Error: nbd_pread: read: command failed: Transport endpoint is not connected (ENOTCONN)
nbdkit: nbdkit command was killed by signal 6

instead of the desired client error with server still alive:

nbd.Error: nbd_pread: read: command failed: Invalid argument (EINVAL)

Fixes: bae4a28d1a
Signed-off-by: Eric Blake <eblake@redhat.com>