eval: Remove unused variable
Genuinely unused variable that GCC did not detect but clang did:

eval.c:233:22: error: unused variable 'cmd' [-Werror,-Wunused-variable]
  CLEANUP_FREE char *cmd = NULL;
                     ^
1 error generated.

(cherry picked from commit 2b597eb35a325a311a0b0807ce8112675e9ab57e)