luks: Various fixes for Clang
With Clang:

luks.c:728:25: error: implicit conversion from enumeration type 'gnutls_digest_algorithm_t' to different enumeration type 'gnutls_mac_algorithm_t' [-Werror,-Wenum-conversion]
  r = gnutls_pbkdf2 (h->hash_alg, &key, &salt, ks->password_iterations,
      ~~~~~~~~~~~~~  ~~~^~~~~~~~
luks.c:764:25: error: implicit conversion from enumeration type 'gnutls_digest_algorithm_t' to different enumeration type 'gnutls_mac_algorithm_t' [-Werror,-Wenum-conversion]
  r = gnutls_pbkdf2 (h->hash_alg, &mkey, &msalt,
      ~~~~~~~~~~~~~  ~~~^~~~~~~~
luks.c:886:35: error: result of comparison of constant 18446744073709551615 with expression of type 'uint32_t' (aka 'unsigned int') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
      if (ks->password_iterations > ULONG_MAX) {
          ~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~

Fixes: commit 468919dce6c5eb57503eacac0f67e5dd87c58e6c