rust: Use clippy suggestion for auto dereference
error: deref which would be done by auto-deref
  --> tests/bare_bones.rs:86:19
   |
86 |     let handle = ((*plugin).open)(0);
   |                   ^^^^^^^^^ help: try this: `plugin`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#explicit_auto_deref
   = note: `-D clippy::explicit-auto-deref` implied by `-D warnings`

(cherry picked from commit 8d1a1c10b599ebe238d01e14025ccf05b14b87b9)