multi-conn: Fix memory leak on error path
Found by Coverity:

  Error: CPPCHECK_WARNING (CWE-401): [#def5]
  nbdkit-1.30.4/filters/multi-conn/multi-conn.c:175: error[memleak]: Memory leak: h
  #  173|       if (h->name == NULL) {
  #  174|         nbdkit_error ("strdup: %m");
  #  175|->       return NULL;
  #  176|       }
  #  177|     }

  Error: RESOURCE_LEAK (CWE-772): [#def6]
  nbdkit-1.30.4/filters/multi-conn/multi-conn.c:166: alloc_fn: Storage is returned from allocation function "calloc".
  nbdkit-1.30.4/filters/multi-conn/multi-conn.c:166: var_assign: Assigning: "h" = storage returned from "calloc(1UL, 32UL)".
  nbdkit-1.30.4/filters/multi-conn/multi-conn.c:175: leaked_storage: Variable "h" going out of scope leaks the storage it points to.
  #  173|       if (h->name == NULL) {
  #  174|         nbdkit_error ("strdup: %m");
  #  175|->       return NULL;
  #  176|       }
  #  177|     }

(cherry picked from commit 3f028f7dc89017e919465591174357e1da71a3ed)