partitioning: Use correct type when checking for non-ASCII
On platforms where 'char' is signed, we were not properly handling
non-ASCII bytes (broken since introduction):

partition-gpt.c: In function ‘create_gpt_partition_table_entry’:
partition-gpt.c:169:23: error: comparison is always false due to limited range of data type [-Werror=type-limits]
  169 |       if (filename[i] > 127)
      |                       ^

Fixes: 2512dc1e
Signed-off-by: Eric Blake <eblake@redhat.com>
(cherry picked from commit f6ef58ea935d9c17c8f362351daa9f9405493343)