build: Ignore warn-error about "ignoring return value of ..."
We want to enable this function generally, but in specific cases we
want to ignore it:

main.c: In function ‘handle_quit’:
main.c:948:3: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
   write (write_quit_fd, &c, 1);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c: In function ‘fork_into_background’:
main.c:1057:3: error: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Werror=unused-result]
   chdir ("/");
   ^~~~~~~~~~~

(cherry picked from commit e90b0a43cd92db651c7464b9a95550930b8b53ad)