curl: Use CURLOPT_PROTOCOLS_STR if available
Old CURLOPT_PROTOCOLS was very awkward to use because we had to
maintain a list of protocols matching the one inside curl.  In curl
7.85.0 this was replaced with a simpler interface which just takes a
comma-separate list of protocols in a string.  At the same time
CURLOPT_PROTOCOLS was deprecated.  If CURLOPT_PROTOCOLS_STR is
available, use it unconditionally.

  curl.c: In function 'curl_open':
  curl.c:526:5: error: 'CURLOPT_PROTOCOLS' is deprecated: since 7.85.0. Use CURLOPT_PROTOCOLS_STR [-Werror=deprecated-declarations]
    526 |     curl_easy_setopt (h->c, CURLOPT_PROTOCOLS, protocols);
        |     ^~~~~~~~~~~~~~~~
  In file included from curl.c:47:
  /usr/include/curl/curl.h:1749:3: note: declared here
   1749 |   CURLOPTDEPRECATED(CURLOPT_PROTOCOLS, CURLOPTTYPE_LONG, 181,
        |   ^~~~~~~~~~~~~~~~~
  curl.c:527:5: error: 'CURLOPT_REDIR_PROTOCOLS' is deprecated: since 7.85.0. Use CURLOPT_REDIR_PROTOCOLS_STR [-Werror=deprecated-declarations]
    527 |     curl_easy_setopt (h->c, CURLOPT_REDIR_PROTOCOLS, protocols);
        |     ^~~~~~~~~~~~~~~~
  /usr/include/curl/curl.h:1755:3: note: declared here
   1755 |   CURLOPTDEPRECATED(CURLOPT_REDIR_PROTOCOLS, CURLOPTTYPE_LONG, 182,
        |   ^~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors