build: Fix GCC diagnostics for GCC 4.4 in RHEL 6
Even with diagnostics turned off, GCC 4.4 in RHEL 6 did not allow
pragma GCC inside function scope, giving errors such as those below.
Make small adjustments to the code to cope with this.  Note this was
actually fixed in GCC 4.8, but testing for GCC >= 5 is easier and fine
because the developers use modern GCC.

virtual-floppy.c: In function ‘visit’:
virtual-floppy.c:340: error: #pragma GCC diagnostic not allowed inside functions
virtual-floppy.c:341: error: #pragma GCC diagnostic not allowed inside functions
virtual-floppy.c:343: error: #pragma GCC diagnostic not allowed inside functions