file: Fix some warnings on macOS
Add __attribute__((unused)) in a few places to fix warn/errors:

file.c:158:1: error: unused function 'is_enotsup' [-Werror,-Wunused-function]
is_enotsup (int err)
^
file.c:699:18: error: unused variable 'h' [-Werror,-Wunused-variable]
  struct handle *h = handle;
                 ^
file.c:700:7: error: unused variable 'r' [-Werror,-Wunused-variable]
  int r;
      ^
file.c:802:2: error: unused label 'out' [-Werror,-Wunused-label]
 out:
 ^~~~