floppy: Don't leak string along error path
Found by Coverity:

  Error: CLANG_WARNING: [#def161]
  nbdkit-1.30.7/plugins/floppy/virtual-floppy.c:432:5: warning[unix.Malloc]: Potential leak of memory pointed to by 'new_file.name'
  #  430|     fi = floppy->files.len;
  #  431|     if (files_append (&floppy->files, new_file) == -1) {
  #  432|->     nbdkit_error ("realloc: %m");
  #  433|       free (host_path);
  #  434|       return -1;

I should note this is not a real problem.  If this code fails (during
floppy disk creation) we will eventually exit with an error.

(cherry picked from commit 18e1504d0bf9871c1414e5d8d51eeb521469b5ce)