server: Fix build when printf is a macro
clang complains on x86 when building

main.c:116:2: error: embedding a #include directive within macro arguments is not supported
 ^

convert nesting include into a string assignment, to same effect but
making it compatible with clang as well

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit e4c825ef36458f5fb423ab6f9acc80b1b3b95a5a)