luks: Avoid memory leak on error path
Found by Coverity:

  Error: CPPCHECK_WARNING (CWE-401): [#def65] [important]
  nbdkit-1.30.7/filters/luks/luks-encryption.c:707: error[memleak]: Memory leak: h
  #  705|     if (memcmp (h->phdr.magic, expected_magic, LUKS_MAGIC_LEN) != 0) {
  #  706|       nbdkit_error ("this disk does not contain a LUKS header");
  #  707|->     return NULL;
  #  708|     }
  #  709|     h->phdr.version = be16toh (h->phdr.version);

Fixes: commit 468919dce6c5eb57503eacac0f67e5dd87c58e6c