eval: Fix memory leak on error path
Found by Coverity:

  Error: RESOURCE_LEAK (CWE-772): [#def20]
  nbdkit-1.30.4/plugins/eval/eval.c:166: alloc_arg: "asprintf" allocates memory that is stored into "script". [Note: The source code implementation of the function has been overridden by a builtin model.]
  nbdkit-1.30.4/plugins/eval/eval.c:172: noescape: Resource "script" is not freed or pointed-to in "strcmp".
  nbdkit-1.30.4/plugins/eval/eval.c:172: noescape: Resource "script" is not freed or pointed-to in "unlink".
  nbdkit-1.30.4/plugins/eval/eval.c:174: leaked_storage: Variable "script" going out of scope leaks the storage it points to.
  #  172|     if (missing && strcmp (script, missing) == 0 && unlink (script) == -1) {
  #  173|       nbdkit_error ("unlink: %m");
  #  174|->     return NULL;
  #  175|     }
  #  176|

Fixes: commit f128f98e8892adf013db52c184ec22c796d176f5
(cherry picked from commit c794d6e3ed8163d0d5ec7a359567ba725999580e)