error: Fix parsing of error-rate=1
Previously we used sscanf to parse this.  However the sscanf
conditionals matched the previous case (sscanf "%lg%%" == 1) because
sscanf's return value doesn't change whether or not the final % is
parsed.

Fixes commit 086a1ceaeb8da4c67787c31580548f7a607b7a7c.

(cherry picked from commit ee2d3b4fea6d4b7618262f85f882374c23674b4a)