mingw: Provide nbdkit_debug() in Windows replacements
Silence compiler warnings such as:

../../../common/replacements/fsync.c: In function 'fsync':
../../../common/replacements/fsync.c:58:5: warning: implicit declaration of function 'nbdkit_debug' [-Wimplicit-function-declaration]
   58 |     nbdkit_debug ("ReadFile: bad handle");
      |     ^~~~~~~~~~~~

(cherry picked from commit b660829f243c10d1fd01efe0a22d3599f5e5ac35)