luks: Disable filter with old GnuTLS in Debian 10
On Debian 10:

luks.c: In function ‘parse_cipher_strings’:
luks.c:574:26: error: ‘GNUTLS_CIPHER_AES_128_XTS’ undeclared (first use in this function); did you mean ‘GNUTLS_CIPHER_AES_128_CCM’?
       h->gnutls_cipher = GNUTLS_CIPHER_AES_128_XTS;
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
                          GNUTLS_CIPHER_AES_128_CCM
luks.c:574:26: note: each undeclared identifier is reported only once for each function it appears in
luks.c:577:26: error: ‘GNUTLS_CIPHER_AES_256_XTS’ undeclared (first use in this function); did you mean ‘GNUTLS_CIPHER_AES_256_CCM’?
       h->gnutls_cipher = GNUTLS_CIPHER_AES_256_XTS;
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
                          GNUTLS_CIPHER_AES_256_CCM
luks.c: In function ‘try_passphrase_in_keyslot’:
luks.c:728:7: error: implicit declaration of function ‘gnutls_pbkdf2’; did you mean ‘gnutls_prf’? [-Werror=implicit-function-declaration]
   r = gnutls_pbkdf2 (h->hash_alg, &key, &salt, ks->password_iterations,
       ^~~~~~~~~~~~~
       gnutls_prf

Because gnutls_pbkdf2 is missing there's no chance of making this
filter work on this platform so it's best to compile it out.

Fixes: commit 468919dce6c5eb57503eacac0f67e5dd87c58e6c
(cherry picked from commit f9f67e483f4aad19ad6101163d32562f13504ca7)