luks: Check return values from malloc more carefully
Found by Coverity:

  Error: GCC_ANALYZER_WARNING (CWE-688): [#def53]
  nbdkit-1.30.7/filters/luks/luks-encryption.c: scope_hint: In function 'calculate_iv'
  nbdkit-1.30.7/filters/luks/luks-encryption.c:175:5: warning[-Wanalyzer-possible-null-argument]: use of possibly-NULL 'iv' where non-null expected
  nbdkit-1.30.7/filters/luks/luks-encryption.c:39: included_from: Included from here.
  /usr/include/string.h:43:14: note: argument 1 of 'memcpy' must be non-null
  #  173|       sector32 = (uint32_t) sector; /* truncate to only lower bits */
  #  174|       sector32 = htole32 (sector32);
  #  175|->     memcpy (iv, &sector32, prefixlen);
  #  176|       memset (iv + prefixlen, 0, ivlen - prefixlen);
  #  177|       break;

  Error: GCC_ANALYZER_WARNING (CWE-688): [#def54]
  nbdkit-1.30.7/filters/luks/luks-encryption.c:184:5: warning[-Wanalyzer-possible-null-argument]: use of possibly-NULL 'iv' where non-null expected
  nbdkit-1.30.7/filters/luks/luks-encryption.c:39: included_from: Included from here.
  /usr/include/string.h:43:14: note: argument 1 of 'memcpy' must be non-null
  #  182|         prefixlen = ivlen;
  #  183|       sector = htole64 (sector);
  #  184|->     memcpy (iv, &sector, prefixlen);
  #  185|       memset (iv + prefixlen, 0, ivlen - prefixlen);
  #  186|       break;

  Error: NULL_RETURNS (CWE-476): [#def55]
  nbdkit-1.30.7/filters/luks/luks-encryption.c:498: returned_null: "malloc" returns "NULL" (checked 86 out of 94 times).
  nbdkit-1.30.7/filters/luks/luks-encryption.c:498: var_assigned: Assigning: "temp" = "NULL" return value from "malloc".
  nbdkit-1.30.7/filters/luks/luks-encryption.c:523: dereference: Dereferencing a pointer that might be "NULL" "temp" when calling "memcpy". [Note: The source code implementation of the function has been overridden by a builtin model.]
  #  521|       gnutls_hash_deinit (hash, temp);
  #  522|
  #  523|->     memcpy (&block[i*digest_bytes], temp, blen);
  #  524|     }
  #  525|

Fixes: commit 468919dce6c5eb57503eacac0f67e5dd87c58e6c