common/include/test-checked-overflow.c: Use different unique name
In code in the test macros TEST_ADD and TEST_MUL such as:

  bool UNIQUE_NAME(_overflow);
  UNIQUE_NAME(_overflow) = ADD_OVERFLOW_FALLBACK ((a), (b), (result));

the same line number (hence unique name) is chosen for the _overflow
variable as for the same named variable inside the expansion of
ADD_OVERFLOW_FALLBACK, resulting in the many pages of errors.  A
sample error is shown below.  Fix this by renaming the variable in the
test macro.

In file included from checked-overflow.h:56,
                 from test-checked-overflow.c:38:
test-checked-overflow.c: In function ‘main’:
checked-overflow.h:135:22: error: declaration of ‘_overflow90’ shadows a previous local [-Werror=shadow]
  135 |     bool UNIQUE_NAME(_overflow);                                      \
      |                      ^~~~~~~~~
unique-name.h:37:35: note: in definition of macro ‘XXUNIQUE_NAME’
   37 | #define XXUNIQUE_NAME(name, line) name ## line
      |                                   ^~~~
unique-name.h:39:27: note: in expansion of macro ‘XUNIQUE_NAME’
   39 | #define UNIQUE_NAME(name) XUNIQUE_NAME (name, __LINE__)
      |                           ^~~~~~~~~~~~
checked-overflow.h:135:10: note: in expansion of macro ‘UNIQUE_NAME’
  135 |     bool UNIQUE_NAME(_overflow);                                      \
      |          ^~~~~~~~~~~
test-checked-overflow.c:44:30: note: in expansion of macro ‘ADD_OVERFLOW_FALLBACK’
   44 |     UNIQUE_NAME(_overflow) = ADD_OVERFLOW_FALLBACK ((a), (b), (result)); \
      |                              ^~~~~~~~~~~~~~~~~~~~~
test-checked-overflow.c:90:3: note: in expansion of macro ‘TEST_ADD’
   90 |   TEST_ADD (umax_max, 0u, &result.umax, false, umax_max);
      |   ^~~~~~~~
test-checked-overflow.c:42:22: note: shadowed declaration is here
   42 |     bool UNIQUE_NAME(_overflow);                                         \
      |                      ^~~~~~~~~

Fixes: commit a7d6e9a907fdabd04573dc3c7b6cedbe5ed13b2e