common/replacements/poll.h: Fix redefinition of poll
MinGW recently added definitions of poll and struct pollfd to
<winsock2.h>.  I cannot find a corresponding implementation of poll in
the library.  ./configure does not detect it.  Also the definition of
struct pollfd conflicts with the normal definition.

In file included from poll.c:46:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/winsock2.h:1185:16: error: redefinition of 'struct pollfd'
 1185 | typedef struct pollfd {
      |                ^~~~~~
In file included from poll.c:42:
poll.h:44:8: note: originally defined here
   44 | struct pollfd {
      |        ^~~~~~
poll.c:65:1: error: conflicting types for 'poll'; have 'int(struct pollfd *, int,  int)'
   65 | poll (struct pollfd *fds, int n, int timeout)
      | ^~~~
In file included from poll.c:42:
poll.h:56:12: note: previous declaration of 'poll' with type 'int(struct pollfd *, int,  int)'
   56 | extern int poll (struct pollfd *fds, int n, int timeout);
      |            ^~~~

This is essentially the same method proposed by Bruno Haible here:
https://lists.gnu.org/archive/html/bug-gnulib/2019-06/msg00124.html