error: Fix all error-*-file parameters.
These didn't work because of copy and paste errors in
commit 086a1ceaeb8da4c67787c31580548f7a607b7a7c
and commit f649b53c037681e897471aa438758a07f067d624.

Thanks: Martin Kletzander
(cherry picked from commit 58fd4d14c71f68c11fcf8690082b7708d9ec7a19)