cc: Use 'error' after it was assigned
I checked the core server code and it does use the same
'if ((error = dlerror ()) != NULL)' condition, but uses error rather
than dlerror when printing the error message.

Found by Coverity:

  Error: CLANG_WARNING: [#def90]
  nbdkit-1.30.7/plugins/cc/cc.c:245:8: warning[deadcode.DeadStores]: Although the value stored to 'error' is used in the enclosing expression, the value is never actually read from 'error'
  #  243|     dlerror ();
  #  244|     *(void **) (&plugin_init) = dlsym (dl, "plugin_init");
  #  245|->   if ((error = dlerror ()) != NULL) {
  #  246|       nbdkit_error ("no plugin_init symbol found: %s", dlerror ());
  #  247|       return -1;

Fixes: commit a4339e3c3c17d8b95ddf0b20cf015de5078620ec