server: exportname cannot be NULL.
The fix is to only add exportname to the URI if it's not "" (rather
than not NULL, because it cannot be NULL).

 Error: FORWARD_NULL (CWE-476): [#def30]
 nbdkit-1.15.7/server/captive.c:74: var_compare_op: Comparing "exportname" to null implies that "exportname" might be null.
 nbdkit-1.15.7/server/captive.c:92: var_deref_model: Passing null pointer "exportname" to "shell_quote", which dereferences it.
 #   90|     /* Expose $exportname. */
 #   91|     fprintf (fp, "exportname=");
 #   92|->   shell_quote (exportname, fp);
 #   93|     putc ('\n', fp);
 #   94|

Bug found by Coverity.