perl: Move GCC diagnostic ignored earlier
Since updating to perl 5.36, the -Wshadow warn/error now occurs when
including the <perl.h> header file, rather than later on when a macro
is used.  Because the GCC diagnostic ignored line appeared after
<perl.h> was included it had no effect.  Moving it before the
inclusion works around this.  The error was:

In file included from /usr/lib64/perl5/CORE/perl.h:4155,
                 from perl.c:47:
/usr/lib64/perl5/CORE/sv_inline.h: In function 'Perl_newSV_type':
/usr/lib64/perl5/CORE/handy.h:97:35: error: declaration of 'p_' shadows a previous local [-Werror=shadow]
   97 | #  define MUTABLE_PTR(p) ({ void *p_ = (p); p_; })
      |                                   ^~

(cherry picked from commit 754f1d46d14b8c97133885fb1422697177e40722)