perl: Auto-disable on mingw
Attempting to build perl on mingw fails horribly with:

libtool: compile:  i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../../../plugins/perl -I../.. -I../../../include -I../../include -I../../../common/include -I../../../common/utils -D_REENTRANT -D_GNU_SOURCE -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/lib64/perl5/CORE -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -MT nbdkit_perl_plugin_la-perl.lo -MD -MP -MF .deps/nbdkit_perl_plugin_la-perl.Tpo -c ../../../plugins/perl/perl.c  -DDLL_EXPORT -DPIC -o .libs/nbdkit_perl_plugin_la-perl.o
Assembler messages:
Fatal error: no compiled in support for x86_64
cc1: error: plugin support is disabled; configure with --enable-plugin
cc1: sorry, unimplemented: 64-bit mode not compiled in

Let's catch this at configure time, at which point we no longer need
to explicitly enable/disable perl at CI time (although we still want
to force --enable-perl on at least some of our other containers).

(cherry picked from commit 4446896fe3cff6f33f1c1ca75518af0d5e72da0c)