server: Limit number of fds which can be passed in through socket activation.
 Error: TAINTED_SCALAR (CWE-20): [#def43]
 nbdkit-1.15.7/server/socket-activation.c:70: tainted_data_return: Function "getenv" returns tainted data.
 nbdkit-1.15.7/server/socket-activation.c:70: var_assign: Assigning: "s" = "getenv", which taints "s".
 nbdkit-1.15.7/server/socket-activation.c:73: tainted_data_transitive: Call to function "nbdkit_parse_unsigned" with tainted argument "s" transitively taints "nr_fds".
 nbdkit-1.15.7/server/socket-activation.c:81: tainted_data: Using tainted variable "nr_fds" as a loop boundary.
 #   79|
 #   80|     /* So the file descriptors don't leak into child processes. */
 #   81|->   for (i = 0; i < nr_fds; ++i) {
 #   82|       fd = FIRST_SOCKET_ACTIVATION_FD + i;
 #   83|       if (fcntl (fd, F_SETFD, FD_CLOEXEC) == -1) {

Bug found by Coverity.