common/include/test-array-size.c: Avoid Clang warning
On Clang with warn-error enabled:

test-array-size.c:44:20: error: variable 's0' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
static const char *s0[] = { };
                   ^
test-array-size.c:45:20: error: variable 's1' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
static const char *s1[] = { "a" };
                   ^

(etc)

Updates: commit 0fa23df5cd5dc97a55857416ea81d5de6d867c18
(cherry picked from commit 90f5dbf78bb56cb00d6b3c58fa0a9b390d50e25e)