ocaml: Declare that we use caml_-namespaced symbols, for OCaml 4.14
Before OCaml 3.08, the language used a lot of non-namespaced symbols
such as “copy_string” (replaced by “caml_copy_string”) and many others.

Starting with OCaml 3.08 and before 5.00 it was possible to use the
non-namespaced symbols without any special changes.  But you could
define -DCAML_NAME_SPACE to declare that you only use caml_* prefixed
(ie. namespaced) symbols.

Starting with OCaml 4.14, using non-namespaced symbols causes a
deprecation warning.

Because “flush” happens to be both a non-namespaced OCaml symbol and
something we use all over nbdkit, compiling nbdkit-ocaml-plugin with
OCaml 4.14 caused the following warning/error:

  ../../include/nbdkit-plugin.h:119:13: error: "flush" is deprecated: use "caml_flush" instead [-Werror]
    119 |   int (*flush) (void *handle, uint32_t flags);
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

The easiest way to fix this (since we don't want or use non-namespaced
symbols) is to define -DCAML_NAME_SPACE.

(cherry picked from commit dd50c8052320c1df38eaa6637dd11af7210177e8)