stats: Fix various warnings in the filter
stats.cpp: In function 'int get_alignment(size_t)':
stats.cpp:118:13: error: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Werror=sign-compare]
  118 |   while(++i < sizeof (powers)/sizeof(powers[0])) {
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
stats.cpp: In function 'void inc_blksize_ctr(blksize_hist_t&, size_t, size_t)':
stats.cpp:211:15: error: catching polymorphic type 'class std::bad_alloc' by value [-Werror=catch-value=]
  211 |   catch (std::bad_alloc) {
      |               ^~~~~~~~~
stats.cpp: In function 'void print_align_hist(const std::unordered_map<int, long unsigned int>&)':
stats.cpp:261:33: error: format '%zu' expects argument of type 'size_t', but argument 3 has type 'int' [-Werror=format=]
  261 |       fprintf (fp, "         %2zu+ bit-aligned: %4.1f%% (%zu)\n",
      |                              ~~~^
      |                                 |
      |                                 long unsigned int
      |                              %2u
  262 |                bits, static_cast<double> (requests) / total * 100, requests);
      |                ~~~~
      |                |
      |                int
stats.cpp:269:33: error: format '%zu' expects argument of type 'size_t', but argument 3 has type 'int' [-Werror=format=]
  269 |       fprintf (fp, "         %2zu bit aligned: %5.1f%% (%zu)\n",
      |                              ~~~^
      |                                 |
      |                                 long unsigned int
      |                              %2u
  270 |               bits, static_cast<double>(requests*100) / total, requests);
      |               ~~~~
      |               |
      |               int

Fixes: commit 99a9aa94404f6cf82de390ba8fd8c2e45a5d5149