rust: Use clippy suggestion for Box default syntax
Multiple warnings like this:

    Checking nbdkit v0.2.0 (/builds/nbdkit/nbdkit/plugins/rust)
error: `Box::new(_)` of default value
  --> examples/ramdisk.rs:55:9
   |
55 |         Box::new(RamDisk::default())
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `Box::<RamDisk>::default()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#box_default
   = note: `-D clippy::box-default` implied by `-D warnings`

(cherry picked from commit 9f41fcc5edf059cb6b0c626b3e1fab2da39df048)