file: Fix leaked file descriptor on error path
Found by Coverity:

  Error: RESOURCE_LEAK (CWE-772): [#def23]
  nbdkit-1.30.4/plugins/file/file.c:394: open_fn: Returning handle opened by "open". [Note: The source code implementation of the function has been overridden by a user model.]
  nbdkit-1.30.4/plugins/file/file.c:394: var_assign: Assigning: "dfd" = handle returned from "open(directory, 589824)".
  nbdkit-1.30.4/plugins/file/file.c:406: leaked_handle: Handle variable "dfd" going out of scope leaks the handle.
  #  404|     if (h == NULL) {
  #  405|       nbdkit_error ("malloc: %m");
  #  406|->     return NULL;
  #  407|     }
  #  408|

(cherry picked from commit 9edbe3a37815dbdd2ab6efac35a23e95e5c42986)