rust: Use correct char type for characters
On Arm platforms which use unsigned char:

error[E0308]: mismatched types
    --> src/lib.rs:1353:29
     |
1353 | ...                   (*sun).sun_path.as_mut_ptr(), 14);
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`
     |
     = note: expected raw pointer `*mut i8`
                found raw pointer `*mut u8`

See also earlier commit 413f3fa5a0c7c8d35fb273fb0ed62ad73ed7a4f5.

(cherry picked from commit e8a30b75097abbdf3c4ef488d1492edff133036d)