tests/test.c: Remove supposed VLA.
Apparently array of const int size is treated by GCC as a VLA:

test.c: In function ‘test_start_nbdkit’:
test.c:141:5: error: ISO C90 forbids array ‘argv’ whose size can’t be evaluated [-Werror=vla]
  141 |     const char *argv[MAX_ARGS+1];
      |     ^~~~~

Fixes commit 8ea4d21748f837d00b2e3c31f29cea0e6f90649a.

(cherry picked from commit b9c6f7aa21c46acb160acb147fb21f5fcb099809)