rust: Add resolver feature
On Debian 11:

cargo build --release
    Updating crates.io index
 Downloading crates ...
  Downloaded libc v0.2.128
error: failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.128/Cargo.toml`
Caused by:
  feature `resolver` is required
  consider adding `cargo-features = ["resolver"]` to the manifest