server: Initialize ‘buf’ to avoid GCC 9.0.1 warning.
GCC 9.0.1 isn't smart enough to work out that buf is initialized on
all the relevant paths that lead to backend->pwrite being called.  By
initializing it we can avoid the warning.

protocol.c: In function ‘protocol_recv_request_send_reply’:
protocol.c:241:9: error: ‘buf’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  241 |     if (backend->pwrite (backend, conn, buf, count, offset, f, &err) == -1)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
protocol.c:614:9: note: ‘buf’ was declared here
  614 |   char *buf;
      |         ^~~

(cherry picked from commit b8bde3b1c1089b31c0dce187bdb4ceb82aef9820)