common/utils/vector.h: Fix pragmas on GCC.
In file included from vector.c:38:
vector.h:47: error: ignoring ‘#pragma clang diagnostic’ [-Werror=unknown-pragmas]
   47 | #pragma clang diagnostic ignored "-Wunused-function"
      |
vector.h:48: error: ignoring ‘#pragma clang diagnostic’ [-Werror=unknown-pragmas]
   48 | #pragma clang diagnostic ignored "-Wduplicate-decl-specifier"
      |
cc1: all warnings being treated as errors

Fixes: commit 78f5e18729f24419f596ad770a45b28e0c67e8f9
(cherry picked from commit a5c4f23288b73dd0147a53335abe1aa3ebfda9a2)