server: Fix clang warning about tautological comparison
public.c:834:19: error: result of comparison of constant 9223372036854775807 with expression of type 'pid_t' (aka 'int') is always true [-Werror,-Wtautological-constant-out-of-range-compare]
    if (ucred.pid <= INT64_MAX)
        ~~~~~~~~~ ^  ~~~~~~~~~
public.c:840:19: error: result of comparison of constant 9223372036854775807 with expression of type 'uid_t' (aka 'unsigned int') is always true [-Werror,-Wtautological-constant-out-of-range-compare]
    if (ucred.uid <= INT64_MAX)
        ~~~~~~~~~ ^  ~~~~~~~~~
public.c:846:19: error: result of comparison of constant 9223372036854775807 with expression of type 'gid_t' (aka 'unsigned int') is always true [-Werror,-Wtautological-constant-out-of-range-compare]
    if (ucred.gid <= INT64_MAX)
        ~~~~~~~~~ ^  ~~~~~~~~~
3 errors generated.

(cherry picked from commit 3b3120b9c61ab5bc55ac25443b01b5a93cee2b86)