common: utils: Use include/ directory to get <nbdkit-plugin.h>
This worked before because nbdkit was installed by the system package
manager, but if not:

  utils.c:42:10: fatal error: nbdkit-plugin.h: No such file or directory
     42 | #include <nbdkit-plugin.h>
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.

Fixes commit 96b468d2e4214d15d722bd44db289d95e137280a.