vddk: Silence gcc warning on asprintf
vddk.c: In function 'perform_reexec':
vddk.c:323:5: error: ignoring return value of 'asprintf' declared with attribute 'warn_unused_result' [-Werror=unused-result]
  323 |     asprintf (&library, "%s:%s", prepend, env);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The warning is a false positive (since we check for library == NULL
just afterwards, which is equally effective at catching failure); this
is one function where I'm not sure I agree with glibc's choice to mark
it w_u_r.  But it's easy enough to work around.

Signed-off-by: Eric Blake <eblake@redhat.com>