xz: h->c is not NULL here, we don't need to check it.
 Error: FORWARD_NULL (CWE-476): [#def13]
 nbdkit-1.15.7/filters/xz/xz.c:125: var_compare_op: Comparing "h->c" to null implies that "h->c" might be null.
 nbdkit-1.15.7/filters/xz/xz.c:132: var_deref_model: Passing null pointer "h->c" to "free_blkcache", which dereferences it. (The dereference is assumed on the basis of the 'nonnull' parameter attribute.)
 #  130|
 #  131|     xzfile_close (h->xz);
 #  132|->   free_blkcache (h->c);
 #  133|     free (h);
 #  134|   }

 Error: CLANG_WARNING: [#def14]
 nbdkit-1.15.7/filters/xz/xz.c:132:3: warning: Null pointer passed as an argument to a 'nonnull' parameter
 #  free_blkcache (h->c);
 #  ^              ~~~~
 nbdkit-1.15.7/filters/xz/xz.c:125:7: note: Assuming field 'c' is null
 #  if (h->c) {
 #      ^~~~
 nbdkit-1.15.7/filters/xz/xz.c:125:3: note: Taking false branch
 #  if (h->c) {
 #  ^
 nbdkit-1.15.7/filters/xz/xz.c:132:3: note: Null pointer passed as an argument to a 'nonnull' parameter
 #  free_blkcache (h->c);
 #  ^              ~~~~
 #  130|
 #  131|     xzfile_close (h->xz);
 #  132|->   free_blkcache (h->c);
 #  133|     free (h);
 #  134|   }

Bug found by Coverity.