perl: Skip CI builds on newer FreeBSD
perl is causing odd compiler errors, such as on FreeBSD 13:

In file included from /usr/local/lib/perl5/5.32/mach/CORE/sbox32_hash.h:4:
/usr/local/lib/perl5/5.32/mach/CORE/zaphod32_hash.h:164:5: error: '(' and '{' tokens introducing statement expression appear in different macro expansion contexts [-Werror,-Wcompound-token-split-by-macro]
    ZAPHOD32_SCRAMBLE32(state[2],0x9c5cc4e9);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/lib/perl5/5.32/mach/CORE/zaphod32_hash.h:80:38: note: expanded from macro 'ZAPHOD32_SCRAMBLE32'
#define ZAPHOD32_SCRAMBLE32(v,prime) STMT_START {  \
                                     ^~~~~~~~~~

It's easier to just ignore perl on these platforms than to worry about
when community will fix the compilation issue.