RHEL 7: curl: Fix plugin for older curl which lacks SMB support.
RHEL 7 has curl-7.29.0-51.el7 which lacks SMB support so you would see
the error below.  These are #defines in newer curl so we can simply
make the code conditional.

curl.c:121:12: error: 'CURLPROTO_SMB' undeclared here (not in a function)
   { "smb", CURLPROTO_SMB },
            ^
curl.c:122:13: error: 'CURLPROTO_SMBS' undeclared here (not in a function)
   { "smbs", CURLPROTO_SMBS },
             ^