floppy: Check if malloc really returned NULL on out of memory path.
We were checking the wrong return value.

Found by Coverity:

Error: REVERSE_INULL (CWE-476): [#def5]
nbdkit-1.7.10/plugins/floppy/directory-lfn.c:481: deref_ptr: Directly dereferencing pointer "out".
nbdkit-1.7.10/plugins/floppy/directory-lfn.c:482: check_after_deref: Null-checking "out" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
  480|     outlen = outalloc;
  481|     *out = malloc (outlen + 1);
  482|->   if (out == NULL) {
  483|       nbdkit_error ("malloc: %m");
  484|       iconv_close (ic);