curl: Correctly check for errors when using getline
Found by Coverity:

  Error: NO_EFFECT (CWE-398): [#def100]
  nbdkit-1.30.7/plugins/curl/scripts.c:333: unsigned_compare: This greater-than-or-equal-to-zero comparison of an unsigned value is always true. "(len = getline(&line, &linelen, fp)) >= 0UL".
  #  331|     fp = fopen (tmpfile, "r");
  #  332|
  #  333|->   if (fp && (len = getline (&line, &linelen, fp)) >= 0) {
  #  334|       if (len > 0 && line[len-1] == '\n')
  #  335|         line[len-1] = '\0';

I checked and fixed other uses of getline in the same file.

Fixes: commit dcba0f0b62ed772bf4dd4849043d8f7bec0fd127
(cherry picked from commit 694effecfaed5b83af0f36b487495dac9e7d860d)