build: Silence some cppcheck warnings [partial port]
Original commit message:

I ran:
$ cppcheck --cppcheck-build-dir=cache/cppcheck -q -I . -I common/include/ \
  -I include/ -I lib/ -I common/utils/ -i generator/ .

then inspected the output.  cppcheck correctly flags:

copy/file-ops.c:423:10: portability: 'data' is of type 'void *'. When using void pointers in calculations, the behaviour is undefined. Arithmetic operations on 'void *' is a GNU C extension, which defines the 'sizeof(void)' to be 1. [arithOperationsOnVoidPointer]

examples/copy-libev.c:312:10: style: Local variable 'is_zero' shadows outer function [shadowFunction]

ocaml/nbd-c.c:419:16: portability: Shifting signed 32-bit value by 31 bits is implementation-defined behaviour. See condition at line 416. [shiftTooManyBitsSigned]

It also has several easy-to-fix false positives such as:

lib/opt.c:98:17: error: Uninitialized variable: err [uninitvar]

where the tool failed to see that err was always assigned by the
callback function, or

python/methods.c:357:7: style: Unused variable: ret [unusedVariable]

where the tool prefers redundant ; to delimit use of Python macros
from actual assignments.  I even addressed some of its style
complaints, like:

copy/nbd-ops.c:466:16: style: The scope of the variable 'd' can be reduced...

examples/open-qcow2.c:12:23: style: Parameter 'argv' can be declared with const [constParameter]

common/utils/test-vector.c:53:0: style: The function 'int64_vector_append' is never used. [unusedFunction]

Then there are other false positives that are harder to silence (for
example, it complains about the macros ARRAY_SIZE(), ADD_OVERFLOW(),
MUL_OVERFLOW(); incorrectly suggesting to add const to callback
function signatures; ...)  which I don't try to address here.  So at
this point, it's not yet worth automating a run of cppcheck into our
CI.

Porting notes:

- Only pick the "common/utils/vector.h" and "common/utils/test-vector.c"
  code changes, for bringing nbdkit's common/ subdir closer to that of
  libnbd.

- Extend "__attribute__((__unused__))" to name##_duplicate(). This
  function comes from nbdkit commit 78b72746e547 ("vector: Add
  vector_duplicate function", 2021-08-22), and was not present in libnbd
  at the time of libnbd commit 8fb8ffb53477 ("build: Silence some cppcheck
  warnings", 2022-11-02).

Signed-off-by: Laszlo Ersek <lersek@redhat.com>
(cherry picked from libnbd commit 8fb8ffb534774e4fc9115b484277713285238078)
Message-Id: <20230303075145.177338-4-lersek@redhat.com>
Acked-by: Richard W.M. Jones <rjones@redhat.com>
Acked-by: Eric Blake <eblake@redhat.com>