include: Disable printf format warnings on platforms that don't support %m
Non-glibc platforms generally do not understand the non-standard %m
conversion type.  We actually support this (see: server/vfprintf.c)
but because the platform doesn't think it should work it would give a
warning like:

environ.c: In function 'copy_environ':
environ.c:64:31: error: unknown conversion type character 'm' in format [-Werror=format=]
   64 |       nbdkit_error ("strdup: %m");
      |                               ^