error: Implement .cache
In the error filter, all we need to do is copy-and-paste existing
per-command errors to one more class of commands (well, technically,
this isn't enabled until a later patch flips the default for
.can_cache to pass-through).

Signed-off-by: Eric Blake <eblake@redhat.com>